CREATE TABLE SAMPLE_TABLE (
    ID                BIGINT      NOT NULL,
    VALUE             VARCHAR(24) NOT NULL,
    PROCESS_DATE_FROM TIMESTAMP   NOT NULL,
    PROCESS_DATE_TO   TIMESTAMP   NOT NULL,
    CONSTRAINT SAMPLE_TABLE_PK PRIMARY KEY (ID, PROCESS_DATE_TO)
);

CREATE TABLE SEQUENCE_TABLE (
    NAME       VARCHAR(50) NOT NULL PRIMARY KEY,
    NEXT_VALUE BIGINT      NOT NULL
);
