CREATE TABLE SAMPLE_TABLE (
    ID          BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CODE        VARCHAR(24) NOT NULL,
    VALUE       VARCHAR(24) NOT NULL,
    FROM_DATE   TIMESTAMP        NOT NULL,
    TO_DATE     TIMESTAMP        NOT NULL
);

CREATE TABLE SEQUENCE_TABLE (
    NAME       VARCHAR(50) NOT NULL PRIMARY KEY,
    NEXT_VALUE BIGINT      NOT NULL
);
