CREATE TABLE SAMPLE_TABLE (
    ID                BIGINT      NOT NULL,
    VALUE             VARCHAR(24) NOT NULL,
    PROCESS_DATE_FROM TIMESTAMP   NOT NULL,
    PROCESS_DATE_TO   TIMESTAMP   NOT NULL,
    CONSTRAINT SAMPLE_TABLE_PK PRIMARY KEY (ID, PROCESS_DATE_TO)
);

INSERT INTO SAMPLE_TABLE (ID, VALUE, PROCESS_DATE_FROM, PROCESS_DATE_TO)
VALUES (1, 'one',   '2017-01-01', '2017-01-02');
INSERT INTO SAMPLE_TABLE (ID, VALUE, PROCESS_DATE_FROM, PROCESS_DATE_TO)
VALUES (1, 'two',   '2017-01-02', '2017-01-03');
INSERT INTO SAMPLE_TABLE (ID, VALUE, PROCESS_DATE_FROM, PROCESS_DATE_TO)
VALUES (1, 'three', '2017-01-03', '9999-12-31');

CREATE TABLE SEQUENCE_TABLE (
    NAME       VARCHAR(50) NOT NULL PRIMARY KEY,
    NEXT_VALUE BIGINT      NOT NULL
);
