CREATE TABLE TEST_TABLE (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    VALUE VARCHAR(32),
    CONSTRAINT TEST_TABLE_PK PRIMARY KEY (ID)
);

INSERT INTO TEST_TABLE (VALUE) VALUES ('hoge');
INSERT INTO TEST_TABLE (VALUE) VALUES ('fuga');
INSERT INTO TEST_TABLE (VALUE) VALUES ('piyo');
